"""Release finalisation (step 63): numbers only from a real, large-enough run."""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from grounded.release import ReleaseError, finalise, main, read_report

REPORT = """# Evaluation - golden set

{n} human-labelled bullets (of 213) generated by a:free, b:free with prompt generate-v1; gate = x.

| Metric | Value |
|---|---|
| **Output fabrication rate** (unsupported among kept) | **{out}** |
| Raw fabrication rate (before the gate) | {raw} |
"""


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    for name in ("README.md", "CHANGELOG.md", "docs/releases/v1.0.0.md"):
        (tmp_path / name).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(name, tmp_path / name)
    (tmp_path / "docs/results").mkdir(parents=True)
    return tmp_path


def write(repo: Path, n: int, out: str = "4%", raw: str = "21%") -> None:
    (repo / "docs/results/eval.md").write_text(REPORT.format(n=n, out=out, raw=raw), "utf-8")


URL = "https://huggingface.co/spaces/someone/evidence-grounded-resume-engine"


def test_placeholders_are_filled_from_the_report(repo: Path) -> None:
    write(repo, 120)
    measured = finalise(URL, repo, today="2026-10-05")
    assert (measured.labelled, measured.output, measured.raw) == (120, "4%", "21%")
    readme = (repo / "README.md").read_text("utf-8")
    assert f"<{URL}>" in readme and "DEMO_URL" not in readme
    assert (
        "| Fabrication rate (output) | **4%** of kept bullets unsupported (before the gate: 21%)"
        in readme
    )
    assert "120 human-labelled bullets of 213, from a:free, b:free" in readme
    assert "pending human labels" not in readme
    notes = (repo / "docs/releases/v1.0.0.md").read_text("utf-8")
    assert "4% of kept bullets unsupported (21% before the gate), 120 human-labelled" in notes
    assert "## [1.0.0] - 2026-10-05" in (repo / "CHANGELOG.md").read_text("utf-8")
    with pytest.raises(ReleaseError, match="already finalised"):
        finalise(URL, repo)


def test_refusals(repo: Path) -> None:
    with pytest.raises(ReleaseError, match="not found"):
        finalise(URL, repo)
    write(repo, 60)
    with pytest.raises(ReleaseError, match="only 60 bullets are labelled"):
        finalise(URL, repo)
    with pytest.raises(ReleaseError, match="must look like"):
        finalise("https://example.com/demo", repo)
    (repo / "docs/results/eval.md").write_text("# something else\n", "utf-8")
    with pytest.raises(ReleaseError, match="not a golden-set report"):
        read_report(repo / "docs/results/eval.md")


def test_cli(
    repo: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(repo)
    assert main(["--demo-url", URL]) == 1
    write(repo, 150, out="0%", raw="0%")
    assert main(["--demo-url", URL]) == 0
    captured = capsys.readouterr()
    assert "fabrication 0% (150 labelled)" in captured.out
    assert "every label says 'supported'" in captured.err
