"""Fill the v1.0.0 release placeholders from what was actually measured.

    python -m grounded.release --demo-url https://huggingface.co/spaces/<you>/<space>

Reads the committed golden-set report (`docs/results/eval.md`, written by
`python -m grounded.evals run`) and fills three placeholders: the demo link
in the README, the fabrication rate in the README and the release notes, and
the release date in the changelog. It refuses to run with fewer than 100
human-labelled bullets - Phase 2's exit criterion - so the published number
always comes from a real, sufficiently large run.
"""

from __future__ import annotations

import argparse
import math
import re
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

MIN_LABELLED = 100
README = Path("README.md")
NOTES = Path("docs/releases/v1.0.0.md")
CHANGELOG = Path("CHANGELOG.md")
REPORT = Path("docs/results/eval.md")
PENDING_ROW = re.compile(r"\| Fabrication rate \(output\) \| \*\*pending human labels\*\*[^\n]*\n")


class ReleaseError(ValueError):
    pass


@dataclass(frozen=True)
class Measured:
    labelled: int
    items: int
    models: str
    output: str
    raw: str
    kept: int
    unsupported_kept: int

    @property
    def upper_bound(self) -> float:
        """95% Wilson upper bound on the output fabrication rate.

        "0 of 53" is not proof of zero: with few kept bullets the true rate
        could still be several percent, and the README says how many."""
        n, k, z = self.kept, self.unsupported_kept, 1.96
        if n == 0:
            return 1.0
        p = k / n
        centre = p + z * z / (2 * n)
        spread = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
        return (centre + spread) / (1 + z * z / n)


def read_report(path: Path) -> Measured:
    if not path.exists():
        raise ReleaseError(f"{path} not found - run: python -m grounded.evals run --out {path}")
    text = path.read_text(encoding="utf-8")
    head = re.search(
        r"(\d+) human-labelled bullets \(of (\d+)\) generated by (.+?) with prompt", text
    )
    output = re.search(r"\*\*Output fabrication rate\*\*[^|]*\| \*\*([\d.]+%)\*\*", text)
    raw = re.search(r"Raw fabrication rate \(before the gate\) \| ([\d.]+%)", text)
    kept = re.search(r"\| Bullets kept \| (\d+) of \d+ \|", text)
    if not (head and output and raw and kept):
        raise ReleaseError(f"{path} is not a golden-set report from `grounded.evals run`")
    n = int(kept.group(1))
    return Measured(
        int(head.group(1)),
        int(head.group(2)),
        head.group(3),
        output.group(1),
        raw.group(1),
        n,
        round(n * float(output.group(1).rstrip("%")) / 100),
    )


def finalise(demo_url: str, root: Path = Path(), today: str | None = None) -> Measured:
    if not re.fullmatch(r"https://huggingface\.co/spaces/[\w.-]+/[\w.-]+", demo_url):
        raise ReleaseError("--demo-url must look like https://huggingface.co/spaces/<user>/<space>")
    measured = read_report(root / REPORT)
    if measured.labelled < MIN_LABELLED:
        raise ReleaseError(
            f"only {measured.labelled} bullets are labelled; Phase 2's exit criterion needs "
            f'{MIN_LABELLED}+ - run: python -m grounded.evals label --by "<you>"'
        )
    readme, notes, changelog = (root / p for p in (README, NOTES, CHANGELOG))
    text = readme.read_text(encoding="utf-8")
    if "DEMO_URL" not in text or not PENDING_ROW.search(text):
        raise ReleaseError("README placeholders not found - already finalised?")
    row = (
        f"| Fabrication rate (output) | **{measured.output}** of kept bullets unsupported "
        f"({measured.unsupported_kept} of {measured.kept}; 95% upper bound "
        f"{measured.upper_bound:.0%}) - before the gate: {measured.raw} "
        f"| [golden set](docs/results/eval.md): "
        f"{measured.labelled} human-labelled bullets of {measured.items}, from "
        f"{measured.models}; [ADR-010](docs/adr/0010-golden-set-and-evals.md) |\n"
    )
    text = PENDING_ROW.sub(lambda _: row, text).replace("DEMO_URL", f"<{demo_url}>")
    readme.write_text(text, encoding="utf-8", newline="\n")
    line = (
        f"{measured.output} of kept bullets unsupported ({measured.unsupported_kept} of "
        f"{measured.kept}, 95% upper bound {measured.upper_bound:.0%}; {measured.raw} before "
        f"the gate), {measured.labelled} human-labelled bullets"
    )
    notes.write_text(
        notes.read_text(encoding="utf-8").replace("FABRICATION_LINE", line),
        encoding="utf-8",
        newline="\n",
    )
    date = today or datetime.now(UTC).date().isoformat()
    changelog.write_text(
        changelog.read_text(encoding="utf-8").replace("RELEASE_DATE", date),
        encoding="utf-8",
        newline="\n",
    )
    return measured


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="grounded.release",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--demo-url", required=True)
    args = parser.parse_args(argv)
    try:
        measured = finalise(args.demo_url)
    except ReleaseError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(
        f"filled: demo link, fabrication {measured.output} of {measured.kept} kept "
        f"(95% upper bound {measured.upper_bound:.0%}; {measured.labelled} labelled), date"
    )
    if measured.raw == "0%":
        print(
            "warning: raw fabrication is 0% - every label says 'supported'. Check the labels "
            "were judged, not skimmed, before publishing.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
